### ISSUE TITLE
Fix the CI

### ISSUE THREAD

**Issue by rrousselGit** [invertase/spec#34] opened 2022-10-03 16:06 UTC
Due to the slower environment, the CI fails on some tests.

The issue appears to be that some tests complete before others, breaking the goldens

**Comment by spydon** [comment] 2022-10-03 16:14
You can assign this to me and I'll try to sort it out.

**Comment by spydon** [comment] 2022-10-03 19:10
@rrousselGit this is so strange, is it because the tests are running asynchronously? The tests are passing consistently locally whatevener I do. Any clue how to remedy this?

**Comment by trejdych** [comment] 2022-10-04 07:15
If I've understood the problem correctly it's not CI problem and it's a feature. Passed test go up
![CleanShot 2022-10-04 at 09 08 11](https://user-images.githubusercontent.com/4202808/193756607-097c6777-a47f-4f56-9c97-b13d90c3a734.gif)

We can change that test ('applies path filter only to packages containing those paths') to:
```
      final lastFrame = testRenderer.frames.last;
        expect(lastFrame, contains('PASS  ../b/test/another_test.dart'));
        expect(lastFrame, contains('PASS  test/my_test.dart'));
        expect(lastFrame, isNot(contains('PASS  ../c/test/skipped_test.dart')));
        expect(
          lastFrame,
          endsWith(''' 
Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Time:        00:00:00
'''),
        );
```
instead of: 

```
        expect(
          testRenderer.frames.last,
          '''
 PASS  ../b/test/another_test.dart
 PASS  test/my_test.dart

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Time:        00:00:00
''',
        );
```

It still test applies filters, however doesn't care about the order

**Comment by rrousselGit** [comment] 2022-10-04 08:37
It's a race condition

The problem is that the final output of the CI depends on the order in which tests complete.
If the order in which tests complete changes (which it does in the CI), some tests fail.

**Comment by rrousselGit** [comment] 2022-10-04 08:38
We'd have to either find a way to force the completion order of tests or update the tests to be independent of the completion order.

**Comment by trejdych** [comment] 2022-10-04 10:59
yup, and I thought that spec_cli behaviour is nice. Prints the result as fast as possible. That's why I've proposed to slightly change the tests (Firstly I thought that only one is "affected" but there are little more)

btw. I can sometimes reproduce it locally. It doesn't matter if `spec`, `dart test` or `dart test --test-randomize-ordering-seed=0`

**Comment by spydon** [comment] 2022-10-06 22:41
I followed @trejdych's suggested fix and applied it on all places where it was needed so the PR is now passing and open for review. :)
https://github.com/invertase/spec/pull/35

**Closed** 2022-10-07 12:29 UTC
Labels: bug, hacktoberfest
